# Generated by Django 5.0.7 on 2024-07-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('language', models.CharField(max_length=15, verbose_name='Название')),
                ('version', models.CharField(max_length=15, verbose_name='Версия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('recommended', models.TextField(verbose_name='Рекомендовано')),
                ('date', models.DateTimeField(verbose_name='Создан')),
                ('lessons', models.PositiveSmallIntegerField(verbose_name='Количество уроков')),
                ('tasks', models.TextField(verbose_name='Задания (формат данных уточняется)')),
                ('favorites', models.PositiveIntegerField(verbose_name='Добавлено в избранное')),
                ('purchased', models.PositiveIntegerField(verbose_name='Количество покупок')),
                ('passed', models.PositiveIntegerField(verbose_name='Выдано сертификатов')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
